/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ThemePreviewRouteImport } from './routes/theme-preview'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as AdminKindIndexRouteImport } from './routes/admin.$kind.index'
import { Route as AdminKindSlugRouteImport } from './routes/admin.$kind.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemePreviewRoute = ThemePreviewRouteImport.update({
  id: '/theme-preview',
  path: '/theme-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKindIndexRoute = AdminKindIndexRouteImport.update({
  id: '/$kind/',
  path: '/$kind/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKindSlugRoute = AdminKindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/use-cases': typeof UseCasesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/admin/$kind/$slug': typeof AdminKindSlugRoute
  '/admin/$kind/': typeof AdminKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/use-cases': typeof UseCasesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/admin/$kind/$slug': typeof AdminKindSlugRoute
  '/admin/$kind': typeof AdminKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/use-cases': typeof UseCasesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/admin/$kind/$slug': typeof AdminKindSlugRoute
  '/admin/$kind/': typeof AdminKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/resources'
    | '/theme-preview'
    | '/use-cases'
    | '/blog/$slug'
    | '/features/$slug'
    | '/admin/'
    | '/blog/'
    | '/features/'
    | '/admin/$kind/$slug'
    | '/admin/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/ai-tools'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/resources'
    | '/theme-preview'
    | '/use-cases'
    | '/blog/$slug'
    | '/features/$slug'
    | '/admin'
    | '/blog'
    | '/features'
    | '/admin/$kind/$slug'
    | '/admin/$kind'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/resources'
    | '/theme-preview'
    | '/use-cases'
    | '/blog/$slug'
    | '/features/$slug'
    | '/admin/'
    | '/blog/'
    | '/features/'
    | '/admin/$kind/$slug'
    | '/admin/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiToolsRoute: typeof AiToolsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  ThemePreviewRoute: typeof ThemePreviewRoute
  UseCasesRoute: typeof UseCasesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-preview': {
      id: '/theme-preview'
      path: '/theme-preview'
      fullPath: '/theme-preview'
      preLoaderRoute: typeof ThemePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$kind/': {
      id: '/admin/$kind/'
      path: '/$kind'
      fullPath: '/admin/$kind/'
      preLoaderRoute: typeof AdminKindIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$kind/$slug': {
      id: '/admin/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/admin/$kind/$slug'
      preLoaderRoute: typeof AdminKindSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKindSlugRoute: typeof AdminKindSlugRoute
  AdminKindIndexRoute: typeof AdminKindIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminKindSlugRoute: AdminKindSlugRoute,
  AdminKindIndexRoute: AdminKindIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiToolsRoute: AiToolsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  ThemePreviewRoute: ThemePreviewRoute,
  UseCasesRoute: UseCasesRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
