/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AuthForwardRouteImport } from './routes/auth.forward'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as AdminKindIndexRouteImport } from './routes/admin.$kind.index'
import { Route as AdminKindSlugRouteImport } from './routes/admin.$kind.$slug'
import { Route as ApiPublicCronBabylovegrowthRouteImport } from './routes/api/public/cron/babylovegrowth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForwardRoute = AuthForwardRouteImport.update({
  id: '/forward',
  path: '/forward',
  getParentRoute: () => AuthRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKindIndexRoute = AdminKindIndexRouteImport.update({
  id: '/$kind/',
  path: '/$kind/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKindSlugRoute = AdminKindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronBabylovegrowthRoute =
  ApiPublicCronBabylovegrowthRouteImport.update({
    id: '/api/public/cron/babylovegrowth',
    path: '/api/public/cron/babylovegrowth',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/api/contact': typeof ApiContactRoute
  '/auth/forward': typeof AuthForwardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/admin/$kind/$slug': typeof AdminKindSlugRoute
  '/admin/$kind/': typeof AdminKindIndexRoute
  '/api/public/cron/babylovegrowth': typeof ApiPublicCronBabylovegrowthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/api/contact': typeof ApiContactRoute
  '/auth/forward': typeof AuthForwardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/admin/$kind/$slug': typeof AdminKindSlugRoute
  '/admin/$kind': typeof AdminKindIndexRoute
  '/api/public/cron/babylovegrowth': typeof ApiPublicCronBabylovegrowthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/api/contact': typeof ApiContactRoute
  '/auth/forward': typeof AuthForwardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/admin/$kind/$slug': typeof AdminKindSlugRoute
  '/admin/$kind/': typeof AdminKindIndexRoute
  '/api/public/cron/babylovegrowth': typeof ApiPublicCronBabylovegrowthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/use-cases'
    | '/admin/articles'
    | '/admin/messages'
    | '/api/contact'
    | '/auth/forward'
    | '/blog/$slug'
    | '/features/$slug'
    | '/admin/'
    | '/blog/'
    | '/features/'
    | '/admin/$kind/$slug'
    | '/admin/$kind/'
    | '/api/public/cron/babylovegrowth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/ai-tools'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/use-cases'
    | '/admin/articles'
    | '/admin/messages'
    | '/api/contact'
    | '/auth/forward'
    | '/blog/$slug'
    | '/features/$slug'
    | '/admin'
    | '/blog'
    | '/features'
    | '/admin/$kind/$slug'
    | '/admin/$kind'
    | '/api/public/cron/babylovegrowth'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/use-cases'
    | '/admin/articles'
    | '/admin/messages'
    | '/api/contact'
    | '/auth/forward'
    | '/blog/$slug'
    | '/features/$slug'
    | '/admin/'
    | '/blog/'
    | '/features/'
    | '/admin/$kind/$slug'
    | '/admin/$kind/'
    | '/api/public/cron/babylovegrowth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiToolsRoute: typeof AiToolsRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UseCasesRoute: typeof UseCasesRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  ApiPublicCronBabylovegrowthRoute: typeof ApiPublicCronBabylovegrowthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forward': {
      id: '/auth/forward'
      path: '/forward'
      fullPath: '/auth/forward'
      preLoaderRoute: typeof AuthForwardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$kind/': {
      id: '/admin/$kind/'
      path: '/$kind'
      fullPath: '/admin/$kind/'
      preLoaderRoute: typeof AdminKindIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$kind/$slug': {
      id: '/admin/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/admin/$kind/$slug'
      preLoaderRoute: typeof AdminKindSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/babylovegrowth': {
      id: '/api/public/cron/babylovegrowth'
      path: '/api/public/cron/babylovegrowth'
      fullPath: '/api/public/cron/babylovegrowth'
      preLoaderRoute: typeof ApiPublicCronBabylovegrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKindSlugRoute: typeof AdminKindSlugRoute
  AdminKindIndexRoute: typeof AdminKindIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminKindSlugRoute: AdminKindSlugRoute,
  AdminKindIndexRoute: AdminKindIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForwardRoute: typeof AuthForwardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForwardRoute: AuthForwardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiToolsRoute: AiToolsRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UseCasesRoute: UseCasesRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  ApiPublicCronBabylovegrowthRoute: ApiPublicCronBabylovegrowthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
